server:
  port: ${PORT:8010}

spring:
  application:
    name: service-inventory
  datasource:
    url: jdbc:h2:file:/tmp/data/H2/inventory.db
    username: sa
    password: 
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always