server:
  port: ${PORT:8000}

spring:
  application:
    name: service-orders
  datasource:
    url: jdbc:h2:file:/tmp/data/H2/orders.db
    username: sa
    password: 
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always