POST http://localhost:8010/inventory/deduct
Content-Type: application/json

{
    "orderId": "e731cdc5-1147-40c7-8b90-8b202f7116ea",
    "items": [
        {
            "productId": "ea869476-aef1-4ab3-a7c6-5a2185ee0ad9",
            "quantity": 1
        },
        {
            "productId": "c38f5477-2795-4433-a863-8ab87a4668c1",
            "quantity": 10
        },
        {
            "productId": "7b70219d-ced5-4d4a-878f-81edf037a12b",
            "quantity": 1
        }
    ]
}